
- name: Check for nvm installation
  stat: "path=/home/j/.nvm"
  register: nvm_install

- name: Install nvm
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh
    creates=/home/j/.nvm/nvm.sh
  when: not nvm_install.stat.exists
  become: yes
  become_user: j

- name: Install node and set version
  shell: >
    /bin/zsh -c "source ~/.nvm/nvm.sh && nvm install --lts"
  when: not nvm_install.stat.exists
  become: yes
  become_user: j

