- name: Install tmux with apt
  apt: name=tmux state=present
  become_user: root
  become: true
  become_method: sudo

- name: Symlink .tmux.conf
  file:
    src: "~/.dotfiles/files/tmux.conf"
    dest: "~/.tmux.conf"
    state: link
