- name: Install tmux with apt
  apt: name=tmux state=present
  become_user: j
  become: true

- name: Symlink .tmux.conf
  file:
    src: "~/.dotfiles/files/.tmux.conf"
    dest: "~/.tmux.conf"
    state: link
  become_user: j
  become: true
