- name: Install zsh
  apt: name=zsh state=present
  become: true
  become_user: j
  become_method: sudo

- name: Check for oh-my-zsh installation
  stat: "path=~/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: Install Oh-My-zsh
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh"
    dest: "/home/j/.oh-my-zsh"
    version: master
    update: no
  when: not oh_my_zsh_stat.stat.exists
  become: true
  become_user: j

- name: Check for .zshrc
  stat: path="~/.zshrc"
  register: zshrc_stat
  become_user: j
  become: true

- name: Back up .zshrc
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "~/.zshrc.bak"
  when: zshrc_stat.stat.exists
  become_user: j
  become: true

- name: Remove .zshrc
  command: rm ~/.zshrc
  when: zshrc_stat.stat.exists
  become_user: j
  become: true

- name: Symlink .zshrc
  file:
    src: "~/.dotfiles/files/.zshrc"
    dest: "~/.zshrc"
    state: link
  become_user: j
  become: true

- name: Get zsh path
  command: which zsh
  register: zsh_path

- name: Switch to zsh
  user:
    name: j
    shell: "{{ zsh_path.stdout }}"

